### ISSUE TITLE
represent holons with DAG

### ISSUE THREAD

**Issue by ahdinosaur** [coopinabox/praxis#12]
each holon either hasMany holons or hasOne user.

i think it is worth trying to use Bookshelf before trying an alternative graph database.

http://drtom.ch/posts/2012/02/11/Encoding_and_Querying_Graphs_in_the_Relational_Model/
https://github.com/DrTom/digraph-demo/tree/master/app/models

**Comment by derekrazo** [comment]
Can you unpack this one a bit?

**Comment by ahdinosaur** [comment]
it's mainly a note to myself, but sure.

i've been questioning whether to support holons in the short-term, and after thinking about it and @jfmyers9 saying that if it's the long-term plan it might as well be in the short-term, i've decided to try and include it. now in order to support holons fully, we need to be able to represent a directed, acyclic graph (as described https://github.com/holonomy/id). instead of going all out graph database (like neo4j) as i played with in [the holon branch](https://github.com/ahdinosaur/workclock/tree/holon), i think it makes more sense to stick with Bookshelf. the links provided are relevant info on how to use a relational database to represent DAGs. however, in the short-term, i might just implement flat holons (no subholons) to get the ball rolling, although that might not be possible in a forward-compatible way. design is still a work in progress: https://github.com/ahdinosaur/workclock/blob/master/docs/design.md, needs more hammock cycles.

**Comment by derekrazo** [comment]
Okay cool. This is what I figured. The article on implementing acyclic
graphs with relational dbs is interesting!

**Comment by ahdinosaur** [comment]
instead of representing holons as a DAG, i think it is better and easier to just have `Person`s and `Organization`s which extend from a common `Agent`.
