### ISSUE TITLE
separate node_modules into per-module repos

### ISSUE THREAD

**Issue by ahdinosaur** [coopinabox/praxis#17]
i'll admit, node_modules in src is weird. not a major issue, but this will also help to enforce module decoupling when possible, as that can increase code reusability and reduce future refactoring headaches.

an open question is how to decouple migrations.

**Comment by derekrazo** [comment]
I think the usefulness of this paradigm is largely dependent on the project size. I agree it increases code reusability.

**Comment by ahdinosaur** [comment]
agreed. in the interest of "make it work, make it beautiful, make it fast", we can just write our code all together but with the vigilance to not unnecessarily couple code, then later actually move the code into separate modules.

**Comment by ahdinosaur** [comment]
restructured modules into separate repos.

core app modules changed from the awful `<module>-{client,server,common}` separation into `ciab-<module>` which contains Backbone models, React components, and Backbone router (e.g. [`ciab-actions`](https://github.com/coopinabox/actions)) and `ciab-<module>-api` which contains Bookshelf models and feathers service (e.g. [`ciab-actions-api`](https://github.com/coopinabox/actions-api)).

generalized React components are `ciab-<module>-component` (e.g. [`ciab-header-component`](https://github.com/coopinabox/header-component))

generalized libraries are `ciab-<module>` (e.g. [`ciab-utils`](https://github.com/coopinabox/utils)).

every module has it's own independent dependencies and tests, `praxis` is the module to put them all together and test the integration.
